drop database sis_hospital;

CREATE DATABASE SIS_HOSPITAL;

USE SIS_HOSPITAL;


-- SCRIPT PARA A TABELA TIPOUSUARIO
CREATE TABLE TIPO_USUARIOS (COD_TIPO INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
DESCRICAO_TIPO VARCHAR(10) NOT NULL, TIPO_USUARIO INT NOT NULL);


-- SCRIPT PARA A TABELA USUARIOS
CREATE TABLE USUARIOS (CODIGO_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
LOGIN_USUARIO VARCHAR(25) NOT NULL, SENHA_USUARIO VARCHAR(15) NOT NULL, 
COD_TIPO_USUARIO INT NOT NULL, 
CONSTRAINT TIPO_USUARIOS_COD_TIPO 
FOREIGN KEY (COD_TIPO_USUARIO) REFERENCES TIPO_USUARIOS(COD_TIPO));



-- SCRIPT PARA A TABELA ENDEREÇO
CREATE TABLE ENDERECO (COD_ENDERECO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
END_NOME_RUA VARCHAR(15), END_NUMERO INT, END_BAIRRO VARCHAR(15),
END_COMPLEMENTO VARCHAR(15), END_CIDADE VARCHAR(25), END_CEP VARCHAR(10),
END_UF VARCHAR(2), END_PAIS VARCHAR(15));


-- SCRIPT PARA A TABELA ENFERMAGEM
CREATE TABLE ENFERMAGEM (COD_ENFERMEIRA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_ENFERMEIRA VARCHAR(20) NOT NULL, CRE VARCHAR(20) NOT NULL, 
CPF_ENFERMEIRA VARCHAR(14) NOT NULL, COD_END_ENFERMEIRA INT NOT NULL, 
RG_ENFERMEIRA VARCHAR(20), ORGAO_EXP_RG VARCHAR(8), DATA_EXP_RG DATE, 
EMAIL_ENFERMEIRA VARCHAR(30), COD_TIPO_USUARIO INT NOT NULL, 
-- CONSTRAINT TIPO_USUARIOS_TIPO_USUARIO_FK 
FOREIGN KEY (COD_TIPO_USUARIO) REFERENCES TIPO_USUARIOS(COD_TIPO),
-- CONSTRAINT ENDERECO_COD_END_ENFERMEIRA_FK
FOREIGN KEY (COD_END_ENFERMEIRA) REFERENCES ENDERECO(COD_ENDERECO));


-- SCRIPT PARA A TABELA MEDICOS
CREATE TABLE MEDICOS (COD_MEDICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_MEDICO VARCHAR(20) NOT NULL, CRM VARCHAR(20) NOT NULL, 
ESPECIALIDADE VARCHAR(20) NOT NULL, COD_END_MEDICO INT NOT NULL,
CPF_MEDICO VARCHAR(14) NOT NULL, RG_MEDICO VARCHAR(20), ORGAO_EXP_RG VARCHAR(8),
DATA_EXP_RG DATE, EMAIL_MEDICO VARCHAR(30), COD_TIPO_USUARIO INT NOT NULL, 
-- CONSTRAINT TIPO_USUARIOS_TIPO_USUARIO_FK 
FOREIGN KEY (COD_TIPO_USUARIO) REFERENCES TIPO_USUARIOS(COD_TIPO),
-- CONSTRAINT ENDERECO_COD_END_MEDICO_FK 
FOREIGN KEY (COD_END_MEDICO) REFERENCES ENDERECO(COD_ENDERECO));


-- SCRIPT PARA A TABELA DE PACIENTES
CREATE TABLE PACIENTES (CPF_PACIENTE VARCHAR(14) NOT NULL PRIMARY KEY,
NOME_PACIENTE VARCHAR(20) NOT NULL,
RG_PACIENTE VARCHAR(20), ORGAO_EXP_RG VARCHAR(8), DATA_EXP_RG DATE,
NOME_PAI VARCHAR(20), NOME_MAE VARCHAR(20), COD_END_PACIENTE INT NOT NULL, 
EMAIL_PACIENTE VARCHAR(30), COD_TIPO_USUARIO INT NOT NULL, 
-- CONSTRAINT TIPO_USUARIOS_TIPO_USUARIO_FK
FOREIGN KEY (COD_TIPO_USUARIO) REFERENCES TIPO_USUARIOS(COD_TIPO),
-- CONSTRAINT ENDERECO_COD_END_PACIENTE_FK 
FOREIGN KEY (COD_END_PACIENTE) REFERENCES ENDERECO(COD_ENDERECO));


-- SCRIPT PARA A TABELA DE MARCAÇÃO DE CONSULTAS
CREATE TABLE MARCACAO_CONSULTAS (COD_CONSULTA_MARCADA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_MEDICO_DA_CONSULTA INT NOT NULL, DATA_CONSULTA DATE NOT NULL, 
COD_PACIENTE VARCHAR(14) NOT NULL,
-- CONSTRAINT MEDICOS_COD_MEDICO_FK 
FOREIGN KEY (COD_MEDICO_DA_CONSULTA) REFERENCES MEDICOS(COD_MEDICO),
-- CONSTRAINT PACIENTES_COD_CONSULTA_MARCADA_FK 
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTES(CPF_PACIENTE));


-- SCRIPT PARA A TABELA DE PRONTUARIOS
CREATE TABLE PRONTUARIOS (COD_PRONTUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_CONSULTA_PAC INT NOT NULL, COD_RESULTADO_CONSULTAS INT NOT NULL, 
ID_PACIENTE VARCHAR(14) NOT NULL, 
CONSTRAINT PACIENTES_CPF_PACIENTE_FK 
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(CPF_PACIENTE));


-- SCRIPT PARA A TABELA CONSULTA
CREATE TABLE CONSULTAS (COD_CONSULTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_MEDICO INT NOT NULL, COD_PRONTUARIO INT NOT NULL,
CONSTRAINT PRONTUARIOS_COD_PRONTUARIO_FK 
FOREIGN KEY (COD_PRONTUARIO) REFERENCES PRONTUARIOS(COD_PRONTUARIO));


-- SCRIPT PARA A TABELA RESULTADO DA CONSULTA
CREATE TABLE RESULTADO_CONSULTA (COD_RES_CONSULTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SUSPEITA VARCHAR(100), COD_EXAMES INT NOT NULL, COD_CONSULTA_RES INT NOT NULL,
CONSTRAINT CONSULTAS_COD_CONSULTAS_FK 
FOREIGN KEY (COD_CONSULTA_RES) REFERENCES CONSULTAS(COD_CONSULTA));



-- SCRIPT PARA A TABELA EXAMES
CREATE TABLE EXAMES (COD_EXAMES INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TIPO VARCHAR(25) NOT NULL, EXAME BLOB, COD_RES_CONSULTA_EXAMES INT NOT NULL, 
CONSTRAINT RESULTADO_CONSULTA_COD_RES_CONSULTA_FK 
FOREIGN KEY (COD_RES_CONSULTA_EXAMES) REFERENCES RESULTADO_CONSULTA(COD_RES_CONSULTA));



-- NAO CONSEGUI RESOLVER O PROBLEMA DAS RESTRIÇÕES EM ENFERMAGEM, MEDICOS, PACIENTES E MARCACAO_CONSULTAS


